name: Connection String
on:
  push:
    branches:
      - test
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "DefaultConnection"
          replace: "hakim-livs-testConnection"
          include: "**Program.cs"
